; This file was auto-generated by drush_make
core = 7.x

api = 2

; Modules
projects[admin][version] = "2.0-beta3"

projects[ctools][version] = "1.0-rc1"

projects[date][version] = "2.0-alpha4"

projects[editablefields][version] = "1.0-alpha2"

projects[entity][version] = "1.0-rc1"

projects[features][version] = "1.0-beta4"

projects[flag][version] = "2.0-beta6"

projects[libraries][version] = "1.0"

projects[pathauto][version] = "1.0"

projects[recipe][version] = "1.2"

projects[strongarm][version] = "2.0-beta4"

projects[token][version] = "1.0-beta7"

projects[views][version] = "3.0-rc3"

;Features
projects[nikas_cookbook][subdir] = "custom_features"
projects[nikas_cookbook][type] = "module"
projects[nikas_cookbook][download][type] = "git"
projects[nikas_cookbook][download][url] = "git://github.com/drupallerina/nikas_cookbook.git"
projects[nikas_cookbook][download][branch] = "master"

;Themes
projects[adaptivetheme][version] = "2.1"

; Libraries
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[profiler][download][type] = "get"
libraries[profiler][download][url] = "http://ftp.drupal.org/files/projects/profiler-7.x-2.0-beta1.tar.gz"
libraries[profiler][directory_name] = "profiler"
libraries[profiler][type] = "library"

